### ISSUE TITLE
[error] GeneralException when trying to validate drive id

### ISSUE THREAD

**Issue by MaxH-Kelch** [halliba/az-pipelines-2-sharepoint#20]
Hello,

I am trying to include your task in the release pipeline of my company.
After following your instructions within the Read.Me however, i get this error:

```
{
"statusCode":401,
"code":"generalException",
"requestId":"94e30c19-c51c-4de9-8ae7-43064bc31174",
"date":"2025-05-05T08:10:10.000Z",
"body":"{
        "code":
	"generalException",
	"message":"General exception while processing",
	"innerError":{
		"date":"2025-05-05T08:10:10",
		"request-id":"94e30c19-c51c-4de9-8ae7-43064bc31174",
		"client-request-id":"f6be9752-0197-7a59-926e-fe1dc89bb47d"
		}
	}"
}
```

I registered the app via Microsoft Entra Admin Center, and used these values from there:

![Image](https://github.com/user-attachments/assets/4936f213-ff39-42fe-8345-316dc211bcea)
![Image](https://github.com/user-attachments/assets/c9434efd-0ec1-4c04-b3d9-2b2140588de1)

When using the secret ID instead of the value from the client secret, i get this response:

```
{
"statusCode":401,
"code":"InvalidAuthenticationToken",
"requestId":"92ff744c-979f-4a3c-b057-b774703de475",
"date":"2025-05-05T08:41:19.000Z",
"body":"{
	"code":"InvalidAuthenticationToken",
	"message":"IDX14100: JWT is not well formed, there are no dots (.).
			   The token needs to be in JWS or JWE Compact Serialization Format. 
			   (JWS): 'EncodedHeader.EncodedPayload.EncodedSignature'. 
			   (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.",
	"innerError":{
		"date":"2025-05-05T08:41:19",
		"request-id":"92ff744c-979f-4a3c-b057-b774703de475",
		"client-request-id":"71d778c9-fa64-55a1-51b2-7216ab68bd53"
		}
	}"
}
```
I added these permissions:

![Image](https://github.com/user-attachments/assets/639bf14a-4e07-4568-9e6e-298e8979a52c)

The configured task looks like this:

![Image](https://github.com/user-attachments/assets/38075c20-8fee-47cf-a787-566db6b346bb)

With the YML behind looking like this:

```
variables:
  AzureTenantID: '***'
  AzureSharePointUploadClientID: '***'

steps:
- task: halliba.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint.az-pipelines-2-sharepoint@0
  displayName: 'Upload files to SharePoint: BDB'
  inputs:
    tenantId: '$(AzureTenantID)'
    clientId: '$(AzureSharePointUploadClientID)'
    clientSecret: '$(AzureSharePointUploadClientID)'
    driveId: 'https://***.sharepoint.com/sites/***/Freigegebene%20Dokumente/Development-Release'
    targetFolder: 'Rel_$(ReleaseVersion)'
    sourceFolder: BDB
    contents: '*/***.exe'
    failOnEmptySource: true
```

If you have any idea, what i am doing wrong or what i am missing, i would greatly appreciate some help.
